### PR TITLE
Aid

### PR DESCRIPTION
**Pull request by dcarp**
Update logo, add quote, make the hiring link generic and stable

### CODE REVIEW

**Comment by veelo** [comment]
Thanks. I would have left the unrelated 3fad924 to a separate PR, though. What's wrong with the file mode?

**Comment by veelo** [comment]
Also, the image needs to be scaled down to max 200px x 100px.

**Comment by dcarp** [comment]
> Thanks. I would have left the unrelated [3fad924](https://github.com/veelo/dlang.org/commit/3fad9240dfdce768dc5b44caf116eb358d4921e2) to a separate PR, though. What's wrong with the file mode?

Ok, I'll take it out. That image has executable flags set.

**Comment by veelo** [comment]
I know the quote is AID's slogan, but all other quotes say something about how D is helping or why they use D, or why D is awesome. This PR makes it look more like an add for AID rather than an add for D ;-) It could possibly still be accepted, but might require chipping in as a sponsor :-)

**Comment by dcarp** [comment]
>  know the quote is AID's slogan, but all other quotes say something about how D is helping or why they use D, or why D is awesome. This PR makes it look more like an add for AID rather than an add for D ;-) It could possibly still be accepted, but might require chipping in as a sponsor :-)

The D-Team is just forming right now. so I'll reformulate it to reflect our hopes.

**Comment by veelo** [comment]
> > Thanks. I would have left the unrelated [3fad924](https://github.com/veelo/dlang.org/commit/3fad9240dfdce768dc5b44caf116eb358d4921e2) to a separate PR, though. What's wrong with the file mode?
> 
> Ok, I'll take it out. That image has executable flags set.

Oh right, that's worth fixing.

**Comment by dcarp** [comment]
I resized the image and adapted the text. We will modify the slogan, when we get some more experience with D.

**Comment by dcarp** [comment]
> Oh right, that's worth fixing.

The image executable flag is still in. Should I take it out?

**Comment by veelo** [comment]
> > Oh right, that's worth fixing.
> 
> The image executable flag is still in. Should I take it out?

I think I managed to split it off into a separate [PR](https://github.com/dlang/dlang.org/pull/2668). Your changes should shortly show up in the original PR, I think they'll look good. Thank you, and good luck with the hiring!

**Comment by veelo** [comment]
Merged through cherry-picking.

**Pull request closed without merging**
